name: Deploy to Google Cloud

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            deploy-api-to-cloud:
                description: Deploy api to cloud
                type: boolean
                required: false

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.21
    
        - name: Build
          run: go build -v ./...
    
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v1
          with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v1
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        
        - name: Configure Docker
          run: gcloud auth configure-docker europe-west2-docker.pkg.dev

        - name: Build Docker image
          run: docker build -t europe-west-2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trend-hencher-repo/trend-hencher-api .

        - name: Push Docker image
          run: docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/trend-hencher-repo/trend-hencher-api
    
        - name: Deploy to Cloud Run
          run: |
            gcloud run deploy trend-hencher-api \
              --platform managed \
              --region europe-west2 \
              --allow-unauthenticated \
              --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/trend-hencher-api